// <auto-generated />
using System;
using ElPodeFC.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElPodeFC.Api.Migrations
{
    [DbContext(typeof(ElPodeFCContext))]
    [Migration("20260917235106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElPodeFC.Api.Domain.Actuacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Goles")
                        .HasColumnType("smallint");

                    b.Property<long>("JugadorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Mvp")
                        .HasColumnType("boolean");

                    b.Property<long>("PartidoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Posicion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId", "JugadorId")
                        .IsUnique();

                    b.ToTable("Actuaciones");
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.ClubConfig", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("DiasJuego")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("DiscordUrl")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("HorarioJuego")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Pausado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ClubConfig", t =>
                        {
                            t.HasCheckConstraint("CK_club_config_id", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            ActualizadoEn = new DateTimeOffset(new DateTime(2026, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DiasJuego = new string[0],
                            Pausado = false
                        });
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Formacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Esquema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Formaciones");
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Jugador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Gamertag")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PosicionHabitual")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Medio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchivoRuta")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PartidoId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubidoPor")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("imagen");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Medios");
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Partido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("MarcadorPropio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("MarcadorRival")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("RegistradoPor")
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rival")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.ToTable("Partidos", t =>
                        {
                            t.HasCheckConstraint("CK_partidos_resultado", "\"Resultado\" IN ('G', 'E', 'P')");
                        });
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Actuacion", b =>
                {
                    b.HasOne("ElPodeFC.Api.Domain.Jugador", "Jugador")
                        .WithMany("Actuaciones")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElPodeFC.Api.Domain.Partido", "Partido")
                        .WithMany("Actuaciones")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Medio", b =>
                {
                    b.HasOne("ElPodeFC.Api.Domain.Partido", "Partido")
                        .WithMany("Medios")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Jugador", b =>
                {
                    b.Navigation("Actuaciones");
                });

            modelBuilder.Entity("ElPodeFC.Api.Domain.Partido", b =>
                {
                    b.Navigation("Actuaciones");

                    b.Navigation("Medios");
                });
#pragma warning restore 612, 618
        }
    }
}
